package com.dota2assistant.ui.component;

import com.dota2assistant.gsi.GsiConfig;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextArea;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;
import javafx.scene.text.Font;
import javafx.scene.text.FontWeight;
import javafx.scene.text.Text;
import javafx.scene.text.TextFlow;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import java.io.File;

/**
 * UI component for setting up GSI.
 */
@Component
public class GsiSetupComponent extends BorderPane {
    
    private final GsiConfig gsiConfig;
    
    // Store the default paths for validation
    private static final String WINDOWS_DEFAULT_PATH = "C:\\Program Files (x86)\\Steam\\steamapps\\common\\dota 2 beta\\game\\dota\\cfg\\gamestate_integration\\";
    
    // Get the GSI config name from application properties
    @Value("${gsi.config.name:dota2_draft_assistant_gsi}")
    private String configName;
    
    @Autowired
    public GsiSetupComponent(GsiConfig gsiConfig) {
        this.gsiConfig = gsiConfig;
        initialize();
    }
    
    /**
     * Initializes the GSI setup component.
     */
    private void initialize() {
        setPadding(new Insets(20));
        
        // Header
        Label headerLabel = new Label("Game State Integration Setup");
        headerLabel.setFont(Font.font("System", FontWeight.BOLD, 18));
        
        // Instructions
        TextFlow instructionsFlow = new TextFlow();
        instructionsFlow.setPadding(new Insets(10, 0, 10, 0));
        Text instructions = new Text(
            "Game State Integration (GSI) allows the application to receive live data from Dota 2. " +
            "The GSI configuration is automatically installed when you start the application.\n\n" +
            "If automatic installation failed, you can:\n" +
            "1. Click the 'Install GSI Config' button below to retry automatic installation.\n" +
            "2. Or manually install the configuration file:\n" +
            "   - Copy the configuration below\n" +
            "   - Create a file named 'dota2_draft_assistant_gsi.cfg' in Dota 2's gamestate_integration directory:\n" +
            "     Windows: C:\\Program Files (x86)\\Steam\\steamapps\\common\\dota 2 beta\\game\\dota\\cfg\\gamestate_integration\\\n" +
            "     Mac: ~/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/dota/cfg/gamestate_integration/\n" +
            "     Linux: ~/.steam/steam/steamapps/common/dota 2 beta/game/dota/cfg/gamestate_integration/\n" +
            "3. Restart Dota 2 if it is already running.\n\n" +
            "Once GSI is set up, the application will automatically detect when you're in a draft and provide live recommendations."
        );
        instructionsFlow.getChildren().add(instructions);
        
        // Configuration text area - using the same content as is generated by GsiConfig
        TextArea configTextArea = new TextArea(gsiConfig.generateConfigContent());
        configTextArea.setEditable(false);
        configTextArea.setPrefRowCount(20);
        configTextArea.setWrapText(true);
        
        // Status message
        TextFlow statusFlow = new TextFlow();
        statusFlow.setId("gsiStatusFlow");
        statusFlow.setPadding(new Insets(10, 0, 10, 0));
        
        // Helper method for installation
        Runnable performInstall = () -> {
            boolean success = gsiConfig.installConfig();
            
            if (success) {
                showStatus("GSI config installed successfully!", true);
            } else {
                showStatus("Failed to install GSI config. Please install manually using the configuration below.", false);
            }
        };
        
        // Install button (renamed to Retry Installation to reflect its new role)
        Button installButton = new Button("Retry Installation");
        installButton.setOnAction(e -> {
            // Check if GSI is already installed before reinstalling
            GsiConfig.GsiStatus gsiStatus = gsiConfig.getGsiStatus();
            if (gsiStatus.isConfigInstalled()) {
                // Show confirmation dialog since the config is already working
                javafx.scene.control.Alert alert = new javafx.scene.control.Alert(
                    javafx.scene.control.Alert.AlertType.CONFIRMATION,
                    "GSI config is already installed. Are you sure you want to reinstall it?",
                    javafx.scene.control.ButtonType.YES, 
                    javafx.scene.control.ButtonType.NO
                );
                alert.setTitle("Confirm Reinstall");
                alert.setHeaderText("Reinstall GSI Configuration");
                
                alert.showAndWait().ifPresent(response -> {
                    if (response == javafx.scene.control.ButtonType.YES) {
                        performInstall.run();
                    }
                });
            } else {
                performInstall.run();
            }
        });
        
        // Layout
        HBox buttonBox = new HBox(10);
        buttonBox.setAlignment(Pos.CENTER);
        buttonBox.setPadding(new Insets(10, 0, 10, 0));
        buttonBox.getChildren().add(installButton);
        
        VBox contentBox = new VBox(10);
        contentBox.getChildren().addAll(
                headerLabel,
                instructionsFlow,
                buttonBox,
                statusFlow,
                new Label("GSI Configuration for Manual Installation:"),
                configTextArea
        );
        
        setCenter(contentBox);
        
        // Add initial status text AFTER the component is fully initialized
        javafx.application.Platform.runLater(() -> {
            try {
                // First check if GSI config is already installed
                GsiConfig.GsiStatus gsiStatus = gsiConfig.getGsiStatus();
                if (gsiStatus.isConfigInstalled()) {
                    showStatus("GSI config is already installed and ready to use!", true);
                    // Rename install button to "Reinstall" since config exists
                    installButton.setText("Reinstall GSI Config");
                    return;
                }
                
                // If not installed, proceed with installation
                boolean initialSuccess = gsiConfig.installConfig();
                String fallbackPath = gsiConfig.getFallbackConfigPath();
                String elevationScriptPath = gsiConfig.getElevationScriptPath();
                
                if (initialSuccess && fallbackPath != null && elevationScriptPath != null &&
                   (elevationScriptPath.contains("install_gsi_config_elevated.bat") || 
                    elevationScriptPath.contains("copy_gsi_config"))) {
                    // Direct UAC/sudo prompt was triggered
                    showStatus("Waiting for administrator privileges confirmation...\n" +
                               "Please respond to the system UAC/admin prompt if it appeared.", false);
                    
                    // After a delay, check if the GSI config file exists in the target location
                    java.util.Timer timer = new java.util.Timer();
                    timer.schedule(new java.util.TimerTask() {
                        @Override
                        public void run() {
                            javafx.application.Platform.runLater(() -> {
                                // Check if the config is installed now
                                if (gsiConfig.getGsiStatus().isConfigInstalled()) {
                                    showStatus("GSI config installed successfully with administrator privileges!", true);
                                } else {
                                    showStatus("Admin installation might not have completed. You can click 'Retry Installation' to try again.", false);
                                }
                            });
                        }
                    }, 8000); // Check after 8 seconds
                
                } else if (initialSuccess && fallbackPath != null && elevationScriptPath != null) {
                    // Success but using fallback location and created a manual elevation script
                    String scriptFilename = new File(elevationScriptPath).getName();
                    String scriptDirectory = new File(elevationScriptPath).getParent();
                    
                    // Add a button to run the elevation script
                    Button elevateButton = new Button("Run Admin Installer");
                    elevateButton.getStyleClass().add("action-button");
                    elevateButton.setOnAction(e -> {
                        try {
                            // Open the directory containing the script so the user can run it as admin
                            if (System.getProperty("os.name").toLowerCase().contains("win")) {
                                new ProcessBuilder("explorer.exe", "/select,", elevationScriptPath).start();
                            } else if (System.getProperty("os.name").toLowerCase().contains("mac")) {
                                new ProcessBuilder("open", "-R", elevationScriptPath).start();
                            } else {
                                new ProcessBuilder("xdg-open", scriptDirectory).start();
                            }
                            
                            showStatus("Please run the '" + scriptFilename + "' file with administrator privileges.", false);
                        } catch (Exception ex) {
                            showStatus("Could not open the file browser. Please run the script at: " + elevationScriptPath, false);
                        }
                    });
                    
                    // Add the button to the layout
                    buttonBox.getChildren().add(elevateButton);
                    
                    showStatus("GSI config created in fallback location.\n" +
                              "To complete installation, click 'Run Admin Installer' and run " + scriptFilename + 
                              " with administrator privileges.", false);
                } else if (initialSuccess && fallbackPath != null) {
                    // Success but using fallback location without elevation script
                    showStatus("GSI config created in fallback location:\n" + fallbackPath + "\n" +
                               "You'll need to manually copy this file to your Dota 2 gamestate_integration directory.", false);
                } else if (initialSuccess) {
                    // Direct success in the correct location
                    showStatus("GSI config has been automatically installed!", true);
                } else {
                    // Complete failure
                    showStatus("Automatic installation failed. You can retry or install manually.", false);
                }
            } catch (Exception ex) {
                showStatus("Automatic installation failed. Please install manually.", false);
            }
        });
    }
    
    /**
     * Shows a status message.
     * 
     * @param message The message to show
     * @param success Whether the operation was successful
     */
    private void showStatus(String message, boolean success) {
        TextFlow statusFlow = (TextFlow) lookup("#gsiStatusFlow");
        statusFlow.getChildren().clear();
        
        Text statusText = new Text(message);
        statusText.setFont(Font.font("System", FontWeight.BOLD, 12));
        statusText.setFill(success ? javafx.scene.paint.Color.GREEN : javafx.scene.paint.Color.RED);
        
        statusFlow.getChildren().add(statusText);
    }
    
    /**
     * Gets the GSI server from the configuration.
     * 
     * @return The GSI server instance.
     */
    public com.dota2assistant.gsi.GsiServer getGsiServer() {
        try {
            // Get the GSI server through reflection, since we only have access 
            // to the GsiConfig object directly
            java.lang.reflect.Field gsiServerField = gsiConfig.getClass().getDeclaredField("gsiServer");
            gsiServerField.setAccessible(true);
            
            // Get the GSI server from the field
            return (com.dota2assistant.gsi.GsiServer) gsiServerField.get(gsiConfig);
        } catch (Exception e) {
            // If we can't get the server through reflection, attempt to create a new one
            try {
                // This is a fallback approach to get or create a GSI server
                java.lang.reflect.Method getServerMethod = gsiConfig.getClass().getDeclaredMethod("getGsiServer");
                getServerMethod.setAccessible(true);
                return (com.dota2assistant.gsi.GsiServer) getServerMethod.invoke(gsiConfig);
            } catch (Exception ex) {
                // Log the error but don't throw exception to avoid UI breakage
                System.err.println("Error getting GSI server: " + ex.getMessage());
                return null;
            }
        }
    }
}